name: Deploy to ECS

on:
push:
branches:
- main

env:
AWS_REGION: ap-south-1
ECR_REPOSITORY: todo-api
ECS_CLUSTER: todo-api-cluster
ECS_SERVICE: todo-api-task-service-lh66xgm1
ECR_REGISTRY: 579920977852.dkr.ecr.ap-south-1.amazonaws.com

jobs:
deploy:
runs-on: ubuntu-latest

```
steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ env.AWS_REGION }}

  - name: Login to Amazon ECR
    uses: aws-actions/amazon-ecr-login@v2

  - name: Build Docker Image
    run: |
      docker build -t $ECR_REPOSITORY .

  - name: Tag Docker Image
    run: |
      docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest

  - name: Push Docker Image
    run: |
      docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

  - name: Force ECS Deployment
    run: |
      aws ecs update-service \
        --cluster $ECS_CLUSTER \
        --service $ECS_SERVICE \
        --force-new-deployment \
        --region $AWS_REGION
```
